### ISSUE TITLE
Why make another repository instead of a tag?

### ISSUE THREAD

**Issue by NurMarvin** [vlang/v0.1.25#2]
Title says it all. I don't really see a reason for making it another repository, especially since every other version was released under a version tag.

**Comment by medvednikov** [comment]
Just a tag doesn't work, because a certain v.c is needed as well.

The repo will be removed today, it's no longer needed.

**Comment by NurMarvin** [comment]
Fair enough. I think a branch would've done the trick in that case but I guess everyone has their own ways 💁‍♂️
